spring:
  servlet:
    multipart:
      max-file-size: 1GB
  datasource:
    username: ${pbms_datasource_username:pbms}
    password: ${pbms_datasource_password}
    url: jdbc:mysql://${pbms_datasource_host:127.0.0.1}:${pbms_mysql_port:3306}/${pbms_mysql_schema:pbms}?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: ${pbms_datasource_driver:com.mysql.cj.jdbc.Driver}

log:
  level: INFO

logging:
  config: classpath:logback-spring-prod.xml

picturebed:
  # 必须是绝对路径
  rootpath: ${PBMS_ROOTPATH:upload}
  baseurl: ${PBMS_BASEURL:http://localhost:8080}
  # 支持最大上传大小, 最大为1GB, 默认10MB
  maxSize: 10MB
  supportType: jpg, gif, png

waterMark:
  # 开启水印
  enable: false
  logo:
    # 默认文字水印
    enable: false
    # 水印logo路径,必须命名为logo.jpg
    path: logo
    # 默认logo会重复
    repeat: false
    # logo倾斜角度
    gradient: 30
  # 透明度0-1
  alpha: 0.3
  # 水印文字
  text:
    enable: false
    content: 一夜暴富，一夜暴富

# 压缩相关
compress:
  # 默认关闭压缩
  enable: false
  # 压缩比率(0-1]
  scale: 0.8

# 返回内容
response:
  # 目前支持markdown、url, 默认为markdown
  type: markdown