server:
  port: 8080

picturebed:
  # 使用绝对路径
  rootpath: pbms
  baseurl: http://127.0.0.1:8080
  # 支持最大上传大小, 最大为1GB, 默认10MB
  maxSize: 10MB
  supportType: jpg, gif, png

log:
  level: INFO

# 配置HTTPS
#server.ssl.key-store:                                         # 签名文件
#server.ssl.key-store-password:                                # 签名密码
#server.ssl.keyStoreType:                                      # 密钥仓库类型