server:
  port: 8080

picturebed:
  # 使用绝对路径
  rootpath: upload
  baseurl: http://localhost:8080
  # 支持最大上传大小, 最大为1GB, 默认10MB
  maxSize: 10MB
  supportType: jpg, gif, png

waterMark:
  # 开启水印
  enable: true
  logo:
    # 默认文字水印
    enable: false
    # 水印logo路径,必须命名为logo.jpg
    path: logo
    # 默认logo会重复
    repeat: true
    # logo倾斜角度
    gradient: 30
  # 透明度0-1
  alpha: 0.3
  # 水印文字
  text:
    enable: true
    content: 一夜暴富，一夜暴富

# 压缩相关
compress:
  # 默认关闭压缩
  enable: true
  # 压缩比率(0-1]
  scale: 0.2

# 返回内容
response:
  # 目前支持markdown、url, 默认为markdown
  type: markdown

log:
  level: INFO

# 配置HTTPS
#server.ssl.key-store:                                         # 签名文件
#server.ssl.key-store-password:                                # 签名密码
#server.ssl.keyStoreType:                                      # 密钥仓库类型