spring:
  servlet:
    multipart:
      max-file-size: 1GB
  datasource:
    username: ${pbms_datasource_username:pbms}
    password: ${pbms_datasource_password:123456}
    url: ${pbms_datasource_url:jdbc:h2:./h2/testdb}
    driver-class-name: ${pbms_datasource_driver:org.h2.Driver}
  flyway:
    enabled: true
    clean-disables: true
    table: flyway_schema_history
    baseline-on-migrate: false
    encoding: UTF-8
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        # 不允许远程访问
        web-allow-others: false

# 关闭sql日志
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

log:
  level: DEBUG

logging:
  config: classpath:logback-spring-dev.xml

picturebed:
  # 必须是绝对路径
  rootpath: ${PBMS_ROOTPATH:pbms}
  baseurl: ${PBMS_BASEURL:http://127.0.0.1:8080}
  # 支持最大上传大小, 最大为1GB, 默认10MB
  max-size: 10MB
  support-type: jpg, gif, png